services:
    api:
        build: .
        command: nodejs server.js
        environment:
          - DATABASE_HOST=db
        ports:
            - "7500:7500"
        networks:
          - backend
        
    db:
        build: .
        ports:
            - "1433:1433"
        networks:
          - backend

networks:
  backend:
    driver: brigde